#!/usr/bin/env tsx
/**
 * Derive `data/raw/redactions.json` from the author's hand-redacted reference images.
 *
 * The author painted **solid black rectangles** over location-identifying content (vendor
 * phone stickers, windows, wall art) on the annotated references in `data/raw/_reference/`.
 * Those references are the same photo as the pristine originals in `data/raw/`, at the same
 * resolution, so a black box sits at the same pixel coordinates in both. This script finds
 * the black rectangles and writes them as `mode:"fill"` redactions in the produced-frame
 * pixel space; `npm run dataset:prepare` then blacks out the same regions on the clean,
 * downscaled frames.
 *
 *   npx tsx scripts/derive-redactions.ts      (then: npm run dataset:prepare -- --force)
 */
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, parse } from "node:path";

import { config } from "@/config";

const REF_DIR = "data/raw/_reference";
const OUT = "data/raw/redactions.json";
const MAX_STILL = config.frames.maxStillPx; // same still-frame width as scripts/prepare-dataset.ts
const BLACK = 16; // r,g,b all below this = "black"
const MIN_AREA_FRAC = 0.0006; // ignore specks / genuine shadows smaller than this

type Rect = { x: number; y: number; w: number; h: number; note: string };

function dims(path: string): { w: number; h: number } {
  const out = execFileSync(
    "ffprobe",
    [
      "-v",
      "error",
      "-select_streams",
      "v:0",
      "-show_entries",
      "stream=width,height",
      "-of",
      "csv=s=x:p=0",
      path,
    ],
    { encoding: "utf8" },
  ).trim();
  const [w, h] = out.split("x").map(Number);
  return { w, h };
}

function rgb(path: string, w: number, h: number): Buffer {
  return execFileSync(
    "ffmpeg",
    ["-v", "error", "-i", path, "-f", "rawvideo", "-pix_fmt", "rgb24", "-"],
    { maxBuffer: w * h * 3 + 1024 },
  );
}

/** Bounding boxes of black connected components (4-neighbour), in image pixels. */
function blackBoxes(
  buf: Buffer,
  w: number,
  h: number,
): { x: number; y: number; w: number; h: number }[] {
  const mask = new Uint8Array(w * h);
  for (let i = 0, p = 0; i < mask.length; i++, p += 3) {
    if (buf[p] < BLACK && buf[p + 1] < BLACK && buf[p + 2] < BLACK) mask[i] = 1;
  }
  const seen = new Uint8Array(w * h);
  const minArea = Math.round(w * h * MIN_AREA_FRAC);
  const boxes: { x: number; y: number; w: number; h: number }[] = [];
  const queue = new Int32Array(w * h);

  for (let start = 0; start < mask.length; start++) {
    if (!mask[start] || seen[start]) continue;
    let head = 0;
    let tail = 0;
    queue[tail++] = start;
    seen[start] = 1;
    let minX = w;
    let minY = h;
    let maxX = 0;
    let maxY = 0;
    let area = 0;
    while (head < tail) {
      const idx = queue[head++];
      const x = idx % w;
      const y = (idx - x) / w;
      area++;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
      const nb = [
        x > 0 ? idx - 1 : -1,
        x < w - 1 ? idx + 1 : -1,
        y > 0 ? idx - w : -1,
        y < h - 1 ? idx + w : -1,
      ];
      for (const n of nb) {
        if (n >= 0 && mask[n] && !seen[n]) {
          seen[n] = 1;
          queue[tail++] = n;
        }
      }
    }
    if (area >= minArea) {
      boxes.push({ x: minX, y: minY, w: maxX - minX + 1, h: maxY - minY + 1 });
    }
  }
  return boxes;
}

const refs = existsSync(REF_DIR) ? readdirSync(REF_DIR).filter((f) => /\.(jpe?g)$/i.test(f)) : [];
if (refs.length === 0) {
  console.error(`no reference images in ${REF_DIR}/`);
  process.exit(1);
}

const sources: Record<string, Rect[]> = {};
for (const file of refs) {
  const path = join(REF_DIR, file);
  const { w, h } = dims(path);
  const scale = Math.min(MAX_STILL, w) / w;
  const boxes = blackBoxes(rgb(path, w, h), w, h);
  const key = parse(file).name;
  sources[key] = boxes.map((b) => ({
    x: Math.round(b.x * scale),
    y: Math.round(b.y * scale),
    w: Math.round(b.w * scale),
    h: Math.round(b.h * scale),
    note: "author hand-redaction (black box on the reference image)",
  }));
  console.log(`${key}: ${boxes.length} box(es)`);
}

writeFileSync(
  OUT,
  JSON.stringify(
    {
      _comment:
        "GENERATED by scripts/derive-redactions.ts from data/raw/_reference/*.jpg (author's black-box redactions). Rectangles are in produced-frame pixel space, mode fill. Re-run the deriver if the references change; then npm run dataset:prepare -- --force.",
      defaults: { mode: "fill" },
      sources,
    },
    null,
    2,
  ) + "\n",
);
console.log(`\nwrote ${OUT} (${Object.keys(sources).length} sources)`);
